import { test } from 'node:test';
import assert from 'node:assert';
import {
  OFFICIAL_AUDIT_ITEMS,
  getOfficialAuditBlockers,
  getOfficialAuditSummary
} from './official_audit.ts';

test('OFFICIAL_AUDIT_ITEMS covers the core operational audit areas', () => {
  const categories = new Set(OFFICIAL_AUDIT_ITEMS.map((item) => item.category));

  assert.ok(categories.has('fees'));
  assert.ok(categories.has('receipt'));
  assert.ok(categories.has('master'));
  assert.ok(categories.has('forms'));
  assert.ok(categories.has('insurance'));
  assert.ok(categories.has('security'));
  assert.ok(categories.has('operations'));
});

test('official audit items keep evidence and remaining work explicit', () => {
  for (const item of OFFICIAL_AUDIT_ITEMS) {
    assert.ok(item.title.length > 0);
    assert.ok(item.officialBasis.length > 0);
    assert.ok(item.implementationEvidence.length > 0);
    assert.ok(item.remainingWork.length > 0);
  }
});

test('operations audit does not claim unverified NSIPS output as compliant', () => {
  const item = OFFICIAL_AUDIT_ITEMS.find((candidate) => candidate.id === 'e2e_return_rebilling');
  assert.ok(item);
  assert.ok(item.implementationEvidence.some((evidence) => evidence.includes('未確認NSIPS風自動出力')));
  assert.ok(item.implementationEvidence.some((evidence) => evidence.includes('SHA-256重複防止キー')));
  assert.ok(item.remainingWork.some((work) => work.includes('20営業日')));
  assert.ok(item.sources.some((source) => source.url.includes('/activities/nsips')));
});

test('getOfficialAuditSummary counts status buckets and critical blockers', () => {
  const summary = getOfficialAuditSummary();

  assert.strictEqual(summary.total, OFFICIAL_AUDIT_ITEMS.length);
  assert.strictEqual(
    summary.total,
    summary.verified + summary.implemented + summary.partial + summary.open
  );
  assert.ok(summary.blockers >= 1);
  assert.ok(summary.completionRate >= 0);
  assert.ok(summary.completionRate <= 100);
});

test('getOfficialAuditBlockers returns only unverified critical items', () => {
  const blockers = getOfficialAuditBlockers();

  assert.ok(blockers.length >= 1);
  assert.ok(blockers.every((item) => item.priority === 'critical'));
  assert.ok(blockers.every((item) => item.status !== 'verified'));
});

test('fee audit item tracks operational rule review without claiming full official coverage', () => {
  const feeItem = OFFICIAL_AUDIT_ITEMS.find((item) => item.id === 'reiwa8_fee_logic');

  assert.ok(feeItem);
  assert.ok(feeItem.implementationEvidence.some((evidence) => evidence.includes('検査薬の薬剤料以外')));
  assert.ok(feeItem.implementationEvidence.some((evidence) => evidence.includes('同月2回以上')));
  assert.ok(feeItem.implementationEvidence.some((evidence) => evidence.includes('特別調剤基本料B')));
  assert.ok(feeItem.implementationEvidence.some((evidence) => evidence.includes('保険・公費の有効期間外')));
  assert.ok(feeItem.implementationEvidence.some((evidence) => evidence.includes('患者名、患者ID、薬品名、受付IDを含まない')));
  assert.ok(feeItem.implementationEvidence.some((evidence) => evidence.includes('一括UKEと公式UKEの作成を止められる')));
  assert.ok(feeItem.remainingWork.some((work) => work.includes('残パターン')));
  assert.ok(feeItem.remainingWork.some((work) => work.includes('現物返戻事例')));
});

test('receipt UKE audit item tracks structural validation and coverage evidence', () => {
  const ukeItem = OFFICIAL_AUDIT_ITEMS.find((item) => item.id === 'receipt_uke_spec');

  assert.ok(ukeItem);
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('UKEレコード生成')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('構造検証')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('iryokikan_in_07.pdf')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('YK/RE/HO/KO/SN/JD/MF/SH/CZ/IY/TO/CO/TK/KI/ST/GO')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('公式提出形式の骨格ゲート')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('必須GO不足')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('非標準レコード混入')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('調剤情報CZ')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('70項目順')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('基本料・薬学管理料KI')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('113項目順')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('包括管理料等省略')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('公式提出準備チェック')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('公式算定コード')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('薬局設定')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('receiptFeeCode')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('設定済み件数')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('公式算定コードマスターCSV')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('名称一致')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('候補、重複、未一致')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('画面とCSV')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('レコード種別カバレッジ')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('実装対象15種別')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('主要項目定義')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('調剤サンプルZIP')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('14_RECODEINFO_PHA.CSV')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('読むだけ対応')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('EX/JY/MN/ON/RC')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('SNとMF')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('条件付き公式レコード')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('公式サンプル検証モード')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('KO/KI/TO/STの未観測理由')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('患者情報なし確認リストをCSV')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('項目プロファイル')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('実値を残さず')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('項目形状比較')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('公式だけ')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('生成だけ')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('項目数差')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('空欄差')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('実生成UKE')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('回帰テスト')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('患者情報なし')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('末尾空欄')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('公式サンプル項目数')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('差分レビュー')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('追加項目要突合')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('優先度')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('次アクション')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('SNを最優先生成')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('確認リスト')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('完了条件')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('CSV出力')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('外部保存')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('公式本文の確認結果')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('生成修正へ進める項目')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('実装候補')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('完了条件付き計画')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('記録条件仕様PDF本文')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('主要項目の位置')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('最大項目番号')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('PDF側の項目が多い')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('全項目行')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('レコード別カバレッジ')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('追加定義が必要')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('次対応と完了条件')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('未定義項目をレコード単位の実装計画')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('常時生成')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('全項目定義実装計画に確認結果')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('定義追加準備')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('全項目定義を段階的に追加')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('未定義リストから外せる')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('allFieldsへ追加する候補')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('項目番号、項目名、形式')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('未定義項目が何件減るか')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('解消レコードと残レコード')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('追加候補ごと')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('定義済みスキップ')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('仕様反映案CSV')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('反映後の全項目定義')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('TypeScript断片')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('残対応CSV')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('完了条件つき')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('対象レコード欠落')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('集計不整合が0件')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('完了とするゲートとCSV')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('allFields定義を生成/公式サンプルUKE検証')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('数字形式、桁数')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('allFields検証結果')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('レコード別指摘CSV')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('月次一括UKE')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('allFields検証サマリ')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('患者、レコード種別、項番')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('指摘コードつきの一覧とCSV')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('作成前チェックレポート')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('出力を止めた場合でも確認内容を外部保存')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('一括UKE作成時にallFields指摘CSVを自動保存')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('保存ファイル名を表示')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('確認CSVのファイル名と指摘件数を監査ログ')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('公式提出準備レビューCSV')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('OK受付も含む')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('請求状態を変えず')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('RECEIPTY.CYO')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('請求ロックと監査ログ')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('公式提出用YKレコード8項目')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('電話番号欠落')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('公式提出用RE/HO/KOレコード')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('公費受給者番号')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('公式提出用SH/CZ/IY/TO/CO/TK/KIレコード')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('KI算定日')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('公式提出用SN/JD/MF/STレコード')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('同じレセプト内のHOまたはKO')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('公式提出用GOレコード')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('総件数、総合計点数、マルチボリューム識別情報')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('allFields完了ゲートとCSV')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('設定画面と監査ログ')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('P1-04完了判定')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('複数処方グループの公式UKE期待形状')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('SH 01/02')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('処方グループ数とRP番号')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('処方グループ計画CSV')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('公式処方番号')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('処方箋受付回')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('複数RPのSH/CZ/IY')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('薬剤調製料を配分')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('GO総合計点数と一致')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('確認事項として公式提出準備CSV')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('GO総件数')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('HO/KO受付回数')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('SH/CZ/IY/TK/KI件数')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('集計OKを監査ログ')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('SN/JD/MF/STを生成')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('条件なしの受付では混入させない')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('社保/国保別の公式UKE現物提出試験CLI')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('患者情報なしJSON/CSVに分け')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('受付NG/返戻の原因コード')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('修正前後UKE差分')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('変更項目位置だけで回帰テスト化')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('公式サンプルだけで見るEX/JY/MN/ON/RC')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('通常請求UKEに混入していない')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('SN補助レコード')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('HO/KOの後、JDの前')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('SN条件付き生成UKE')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('非空欄位置')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('形状一致をCSV')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('公式調剤サンプルの現物レコード')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('公式サンプル側の必須抜け・形式不備')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('先頭/末尾/点数突合')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('TK合計情報')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('算定レコード件数')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('YK/RE/JD/SH/TK/ST重複')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('順序崩れ')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('保険薬局コード')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('桁数・数字形式')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('サンプル網羅チェック')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('社保')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('再請求')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('受付前チェック')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('再請求準備前')));
  assert.ok(ukeItem.implementationEvidence.some((evidence) => evidence.includes('再請求理由未入力')));
  assert.ok(ukeItem.remainingWork.some((work) => work.includes('記録条件仕様PDF')));
  assert.ok(ukeItem.remainingWork.some((work) => work.includes('PDF本文')));
  assert.ok(ukeItem.remainingWork.some((work) => work.includes('全フィールド')));
  assert.ok(ukeItem.remainingWork.some((work) => work.includes('GO必須生成')));
  assert.ok(ukeItem.remainingWork.some((work) => work.includes('SN/JD/MF/ST')));
  assert.ok(ukeItem.remainingWork.some((work) => work.includes('現物受付結果')));
  assert.ok(ukeItem.remainingWork.some((work) => work.includes('告示・疑義解釈')));
  assert.ok(ukeItem.remainingWork.some((work) => work.includes('支払基金マスター')));
  assert.ok(ukeItem.remainingWork.some((work) => work.includes('名称一致以外のコード自動付与ルール')));
  assert.ok(!ukeItem.remainingWork.some((work) => work.includes('EX/JY/MN/ON/RCの生成ルール追加')));
  assert.ok(!ukeItem.remainingWork.some((work) => work.includes('SN条件付き生成の公式現物追加突合')));
  assert.ok(ukeItem.remainingWork.some((work) => work.includes('国保連')));
  assert.ok(!ukeItem.remainingWork.some((work) => work.includes('TO/ST')));
  assert.ok(!ukeItem.remainingWork.some((work) => work.includes('サンプルUKEを作成')));
  assert.ok(!ukeItem.remainingWork.some((work) => work.includes('オンライン請求前の受付チェック')));
});

test('security audit item tracks hash-chain evidence and external custody work separately', () => {
  const securityItem = OFFICIAL_AUDIT_ITEMS.find((item) => item.id === 'security_permissions_audit');

  assert.ok(securityItem);
  assert.ok(securityItem.implementationEvidence.some((evidence) => evidence.includes('ハッシュチェーン改ざん検知')));
  assert.ok(securityItem.implementationEvidence.some((evidence) => evidence.includes('責任者保全欄付きJSON')));
  assert.ok(securityItem.implementationEvidence.some((evidence) => evidence.includes('保全台帳CSV')));
  assert.ok(securityItem.implementationEvidence.some((evidence) => evidence.includes('月次棚卸CSV')));
  assert.ok(securityItem.implementationEvidence.some((evidence) => evidence.includes('責任者差し戻し')));
  assert.ok(securityItem.implementationEvidence.some((evidence) => evidence.includes('責任者承認')));
  assert.ok(securityItem.implementationEvidence.some((evidence) => evidence.includes('専用監査ログ')));
  assert.ok(securityItem.implementationEvidence.some((evidence) => evidence.includes('S3 WORM事前確認CLI')));
  assert.ok(securityItem.implementationEvidence.some((evidence) => evidence.includes('非個人情報プローブ')));
  assert.ok(securityItem.implementationEvidence.some((evidence) => evidence.includes('監査ログS3 WORM保全ジョブ')));
  assert.ok(securityItem.implementationEvidence.some((evidence) => evidence.includes('最新ハッシュ照合')));
  assert.ok(securityItem.implementationEvidence.some((evidence) => evidence.includes('監査ログS3 WORM保全の定期実行ジョブ')));
  assert.ok(securityItem.implementationEvidence.some((evidence) => evidence.includes('二重実行抑止')));
  assert.ok(securityItem.implementationEvidence.some((evidence) => evidence.includes('Webhook監視先POST')));
  assert.ok(securityItem.implementationEvidence.some((evidence) => evidence.includes('定期ジョブ点検・通知訓練CLI')));
  assert.ok(securityItem.implementationEvidence.some((evidence) => evidence.includes('患者情報なしのWebhook到達訓練')));
  assert.ok(securityItem.implementationEvidence.some((evidence) => evidence.includes('定期運用継続レビュー')));
  assert.ok(securityItem.implementationEvidence.some((evidence) => evidence.includes('失敗後の復旧点検')));
  assert.ok(securityItem.implementationEvidence.some((evidence) => evidence.includes('初回セットアップチェックリスト')));
  assert.ok(securityItem.implementationEvidence.some((evidence) => evidence.includes('バックアップ訓練')));
  assert.ok(securityItem.implementationEvidence.some((evidence) => evidence.includes('必要な対応を最大2件')));
  assert.ok(securityItem.implementationEvidence.some((evidence) => evidence.includes('CSVを開かなくても次作業')));
  assert.ok(securityItem.implementationEvidence.some((evidence) => evidence.includes('初回セットアップ引き継ぎメモ')));
  assert.ok(securityItem.implementationEvidence.some((evidence) => evidence.includes('判定、次作業、完了数を監査ログ')));
  assert.ok(securityItem.implementationEvidence.some((evidence) => evidence.includes('店舗ごとの権限ロール設定')));
  assert.ok(securityItem.implementationEvidence.some((evidence) => evidence.includes('パスキー紛失時の復旧')));
  assert.ok(securityItem.implementationEvidence.some((evidence) => evidence.includes('スタッフ復旧・退職対応レビューCLI')));
  assert.ok(securityItem.implementationEvidence.some((evidence) => evidence.includes('匿名ケースID')));
  assert.ok(securityItem.implementationEvidence.some((evidence) => evidence.includes('管理者残存')));
  assert.ok(securityItem.implementationEvidence.some((evidence) => evidence.includes('スタッフ名なしJSON/CSV/チェックリスト')));
  assert.ok(securityItem.remainingWork.some((work) => work.includes('本番端末のOSスケジューラ')));
  assert.ok(securityItem.remainingWork.some((work) => work.includes('現物証跡の継続保管')));
  assert.ok(!securityItem.remainingWork.some((work) => work.includes('本番認証')));
  assert.ok(!securityItem.remainingWork.some((work) => work.includes('責任者承認フロー')));
  assert.ok(!securityItem.remainingWork.some((work) => work.includes('自動連携または保存完了検証')));
  assert.ok(!securityItem.remainingWork.some((work) => work.includes('外部WORM保存運用')));
  assert.ok(!securityItem.remainingWork.some((work) => work.includes('最新ハッシュの責任者保全')));
  assert.ok(!securityItem.remainingWork.some((work) => work.includes('改ざん検知、外部保存、エクスポート')));
});

test('printed forms audit item tracks screenshot regression separately from device validation', () => {
  const formsItem = OFFICIAL_AUDIT_ITEMS.find((item) => item.id === 'printed_forms');

  assert.ok(formsItem);
  assert.ok(formsItem.implementationEvidence.some((evidence) => evidence.includes('data-testid')));
  assert.ok(formsItem.implementationEvidence.some((evidence) => evidence.includes('Puppeteerスクリーンショット回帰')));
  assert.ok(formsItem.implementationEvidence.some((evidence) => evidence.includes('CI artifact保存')));
  assert.ok(formsItem.implementationEvidence.some((evidence) => evidence.includes('A4/A5相当の実紙幅')));
  assert.ok(formsItem.implementationEvidence.some((evidence) => evidence.includes('罫線中心の実務紙面')));
  assert.ok(formsItem.implementationEvidence.some((evidence) => evidence.includes('職員用の小さな色印')));
  assert.ok(formsItem.implementationEvidence.some((evidence) => evidence.includes('識別文字は出さず')));
  assert.ok(formsItem.implementationEvidence.some((evidence) => evidence.includes('取り違え防止')));
  assert.ok(formsItem.implementationEvidence.some((evidence) => evidence.includes('実紙確認JSON')));
  assert.ok(formsItem.implementationEvidence.some((evidence) => evidence.includes('個人情報なしレビューJSON/CSV')));
  assert.ok(formsItem.implementationEvidence.some((evidence) => evidence.includes('個人情報なし診断JSON')));
  assert.ok(formsItem.remainingWork.some((work) => work.includes('現物検証')));
  assert.ok(formsItem.remainingWork.some((work) => work.includes('現物サンプル')));
  assert.ok(!formsItem.remainingWork.some((work) => work.includes('スクリーンショット回帰')));
});

test('backup audit item tracks restore drill evidence separately from actual restore', () => {
  const backupItem = OFFICIAL_AUDIT_ITEMS.find((item) => item.id === 'backup_sync_recovery');

  assert.ok(backupItem);
  assert.ok(backupItem.implementationEvidence.some((evidence) => evidence.includes('復旧テスト')));
  assert.ok(backupItem.implementationEvidence.some((evidence) => evidence.includes('監査ログへ記録')));
  assert.ok(backupItem.implementationEvidence.some((evidence) => evidence.includes('ID欠落')));
  assert.ok(backupItem.implementationEvidence.some((evidence) => evidence.includes('同一ID重複')));
  assert.ok(backupItem.implementationEvidence.some((evidence) => evidence.includes('文字化け')));
  assert.ok(backupItem.implementationEvidence.some((evidence) => evidence.includes('必須領域不足')));
  assert.ok(backupItem.implementationEvidence.some((evidence) => evidence.includes('患者CSV/TSV')));
  assert.ok(backupItem.implementationEvidence.some((evidence) => evidence.includes('受付CSV/TSV')));
  assert.ok(backupItem.implementationEvidence.some((evidence) => evidence.includes('在庫CSV/TSV')));
  assert.ok(backupItem.implementationEvidence.some((evidence) => evidence.includes('薬歴CSV/TSV')));
  assert.ok(backupItem.implementationEvidence.some((evidence) => evidence.includes('移行用バックアップJSON')));
  assert.ok(backupItem.implementationEvidence.some((evidence) => evidence.includes('横断レビュー')));
  assert.ok(backupItem.implementationEvidence.some((evidence) => evidence.includes('参照不整合')));
  assert.ok(backupItem.implementationEvidence.some((evidence) => evidence.includes('1日テスト開始可否')));
  assert.ok(backupItem.implementationEvidence.some((evidence) => evidence.includes('個人情報なし診断JSON')));
  assert.ok(backupItem.implementationEvidence.some((evidence) => evidence.includes('バックアップ世代管理CSV')));
  assert.ok(backupItem.implementationEvidence.some((evidence) => evidence.includes('バックアップ外部保存先')));
  assert.ok(backupItem.implementationEvidence.some((evidence) => evidence.includes('閉店時バックアップ予定')));
  assert.ok(backupItem.implementationEvidence.some((evidence) => evidence.includes('外部保存連携JSON')));
  assert.ok(backupItem.implementationEvidence.some((evidence) => evidence.includes('SHA-256')));
  assert.ok(backupItem.implementationEvidence.some((evidence) => evidence.includes('ブラウザ外ジョブ')));
  assert.ok(backupItem.implementationEvidence.some((evidence) => evidence.includes('読み戻し再照合')));
  assert.ok(backupItem.implementationEvidence.some((evidence) => evidence.includes('定期実行')));
  assert.ok(backupItem.implementationEvidence.some((evidence) => evidence.includes('自動振り分け')));
  assert.ok(backupItem.implementationEvidence.some((evidence) => evidence.includes('状態JSON')));
  assert.ok(backupItem.implementationEvidence.some((evidence) => evidence.includes('失敗通知JSON')));
  assert.ok(backupItem.implementationEvidence.some((evidence) => evidence.includes('再実行手順')));
  assert.ok(backupItem.implementationEvidence.some((evidence) => evidence.includes('Webhook監視先')));
  assert.ok(backupItem.implementationEvidence.some((evidence) => evidence.includes('Bearerトークン')));
  assert.ok(backupItem.implementationEvidence.some((evidence) => evidence.includes('S3 WORM')));
  assert.ok(backupItem.implementationEvidence.some((evidence) => evidence.includes('S3 WORM事前確認CLI')));
  assert.ok(backupItem.implementationEvidence.some((evidence) => evidence.includes('バケットVersioning')));
  assert.ok(backupItem.implementationEvidence.some((evidence) => evidence.includes('Object Lock')));
  assert.ok(backupItem.implementationEvidence.some((evidence) => evidence.includes('受領書JSON')));
  assert.ok(backupItem.implementationEvidence.some((evidence) => evidence.includes('監査ログへ記録')));
  assert.ok(backupItem.implementationEvidence.some((evidence) => evidence.includes('ブラウザ外バックアップ書き出しCLI')));
  assert.ok(backupItem.implementationEvidence.some((evidence) => evidence.includes('暗号化バックアップのダウンロード')));
  assert.ok(backupItem.implementationEvidence.some((evidence) => evidence.includes('定期ジョブ点検・通知訓練CLI')));
  assert.ok(backupItem.implementationEvidence.some((evidence) => evidence.includes('スケジューラ登録証跡')));
  assert.ok(backupItem.implementationEvidence.some((evidence) => evidence.includes('定期運用継続レビュー')));
  assert.ok(backupItem.implementationEvidence.some((evidence) => evidence.includes('複数世代の点検受領書')));
  assert.ok(backupItem.implementationEvidence.some((evidence) => evidence.includes('実データ相当移行受入CLI')));
  assert.ok(backupItem.implementationEvidence.some((evidence) => evidence.includes('導入1日テスト計画')));
  assert.ok(backupItem.implementationEvidence.some((evidence) => evidence.includes('責任者レビュー')));
  assert.ok(backupItem.implementationEvidence.some((evidence) => evidence.includes('初日業務を個別判定')));
  assert.ok(backupItem.implementationEvidence.some((evidence) => evidence.includes('匿名確認ID')));
  assert.ok(backupItem.implementationEvidence.some((evidence) => evidence.includes('ダミー証跡を移行受入にしない')));
  assert.ok(backupItem.implementationEvidence.some((evidence) => evidence.includes('患者情報なしCSV')));
  assert.ok(backupItem.remainingWork.some((work) => work.includes('OSスケジューラ')));
  assert.ok(backupItem.remainingWork.some((work) => work.includes('ログイン済みプロファイル')));
  assert.ok(backupItem.remainingWork.some((work) => work.includes('点検受領書の現物継続保管')));
  assert.ok(backupItem.remainingWork.some((work) => work.includes('S3以外のWORM')));
  assert.ok(backupItem.remainingWork.some((work) => work.includes('他社ソフト実データ相当')));
  assert.ok(!backupItem.remainingWork.some((work) => work.includes('本番認証')));
  assert.ok(!backupItem.remainingWork.some((work) => work.includes('自動バックアップ書き出し')));
  assert.ok(!backupItem.remainingWork.some((work) => work.includes('外部保存ジョブの実接続')));
  assert.ok(!backupItem.remainingWork.some((work) => work.includes('専用コネクタ接続')));
  assert.ok(!backupItem.remainingWork.some((work) => work.includes('復旧訓練')));
  assert.ok(!backupItem.remainingWork.some((work) => work.includes('外部保存完了検証')));
});

test('drug master audit item tracks diff and rollback evidence separately from remaining work', () => {
  const drugMasterItem = OFFICIAL_AUDIT_ITEMS.find((item) => item.id === 'drug_master_update');

  assert.ok(drugMasterItem);
  assert.ok(drugMasterItem.implementationEvidence.some((evidence) => evidence.includes('差分CSV')));
  assert.ok(drugMasterItem.implementationEvidence.some((evidence) => evidence.includes('ロールバックJSON')));
  assert.ok(drugMasterItem.implementationEvidence.some((evidence) => evidence.includes('新規追加行削除')));
  assert.ok(drugMasterItem.implementationEvidence.some((evidence) => evidence.includes('廃止薬')));
  assert.ok(drugMasterItem.implementationEvidence.some((evidence) => evidence.includes('レセ電コード欠落')));
  assert.ok(drugMasterItem.implementationEvidence.some((evidence) => evidence.includes('IYレコード')));
  assert.ok(drugMasterItem.implementationEvidence.some((evidence) => evidence.includes('ヘッダー付き')));
  assert.ok(drugMasterItem.implementationEvidence.some((evidence) => evidence.includes('列名')));
  assert.ok(drugMasterItem.implementationEvidence.some((evidence) => evidence.includes('SHA-256')));
  assert.ok(drugMasterItem.implementationEvidence.some((evidence) => evidence.includes('更新元URL')));
  assert.ok(drugMasterItem.implementationEvidence.some((evidence) => evidence.includes('候補リンク')));
  assert.ok(drugMasterItem.implementationEvidence.some((evidence) => evidence.includes('更新候補を抽出')));
  assert.ok(drugMasterItem.implementationEvidence.some((evidence) => evidence.includes('更新元URLへ反映')));
  assert.ok(drugMasterItem.implementationEvidence.some((evidence) => evidence.includes('公式ページを取得')));
  assert.ok(drugMasterItem.implementationEvidence.some((evidence) => evidence.includes('公式URL確認')));
  assert.ok(drugMasterItem.implementationEvidence.some((evidence) => evidence.includes('42項目定義')));
  assert.ok(drugMasterItem.implementationEvidence.some((evidence) => evidence.includes('必須/任意列照合')));
  assert.ok(drugMasterItem.implementationEvidence.some((evidence) => evidence.includes('根拠PDF版')));
  assert.ok(drugMasterItem.implementationEvidence.some((evidence) => evidence.includes('PDF URL')));
  assert.ok(drugMasterItem.implementationEvidence.some((evidence) => evidence.includes('先頭/末尾項目')));
  assert.ok(drugMasterItem.implementationEvidence.some((evidence) => evidence.includes('本文テキスト')));
  assert.ok(drugMasterItem.implementationEvidence.some((evidence) => evidence.includes('差分候補')));
  assert.ok(drugMasterItem.implementationEvidence.some((evidence) => evidence.includes('サーバー経由')));
  assert.ok(drugMasterItem.implementationEvidence.some((evidence) => evidence.includes('検索可能PDF本文')));
  assert.ok(drugMasterItem.implementationEvidence.some((evidence) => evidence.includes('読取不可として止め')));
  assert.ok(drugMasterItem.implementationEvidence.some((evidence) => evidence.includes('OCR/外部抽出済み本文')));
  assert.ok(drugMasterItem.implementationEvidence.some((evidence) => evidence.includes('公式全件ZIP')));
  assert.ok(drugMasterItem.implementationEvidence.some((evidence) => evidence.includes('ZIP内CSV名')));
  assert.ok(drugMasterItem.implementationEvidence.some((evidence) => evidence.includes('CSV/ZIP候補URL')));
  assert.ok(drugMasterItem.implementationEvidence.some((evidence) => evidence.includes('直接取り込める')));
  assert.ok(drugMasterItem.implementationEvidence.some((evidence) => evidence.includes('PMDA公式添付文書HTML')));
  assert.ok(drugMasterItem.implementationEvidence.some((evidence) => evidence.includes('PMDA公式ラベルキューレビューCLI')));
  assert.ok(drugMasterItem.implementationEvidence.some((evidence) => evidence.includes('旧targetDrug単数スキーマ')));
  assert.ok(drugMasterItem.implementationEvidence.some((evidence) => evidence.includes('KEGG信号')));
  assert.ok(drugMasterItem.implementationEvidence.some((evidence) => evidence.includes('通信再試行')));
  assert.ok(drugMasterItem.implementationEvidence.some((evidence) => evidence.includes('PMDA候補なし')));
  assert.ok(drugMasterItem.implementationEvidence.some((evidence) => evidence.includes('PMDA検索候補なしレビューCLI')));
  assert.ok(drugMasterItem.implementationEvidence.some((evidence) => evidence.includes('no_official_label_found')));
  assert.ok(drugMasterItem.implementationEvidence.some((evidence) => evidence.includes('責任者承認')));
  assert.ok(!drugMasterItem.remainingWork.some((work) => work.includes('自動取得')));
  assert.ok(!drugMasterItem.remainingWork.some((work) => work.includes('更新候補選択UI')));
  assert.ok(!drugMasterItem.remainingWork.some((work) => work.includes('公式ZIP候補URL')));
  assert.ok(!drugMasterItem.remainingWork.some((work) => work.includes('ブラウザ内展開と取り込み')));
  assert.ok(drugMasterItem.remainingWork.some((work) => work.includes('外部OCRエンジン')));
  assert.ok(drugMasterItem.remainingWork.some((work) => work.includes('画像化PDFの現物サンプル')));
  assert.ok(!drugMasterItem.remainingWork.some((work) => work.includes('OCR/外部抽出エンジン連携')));
  assert.ok(!drugMasterItem.remainingWork.some((work) => work.includes('仕様PDFファイル')));
  assert.ok(!drugMasterItem.remainingWork.some((work) => work.includes('本文抽出の自動化')));
  assert.ok(!drugMasterItem.remainingWork.some((work) => work.includes('差分候補')));
  assert.ok(!drugMasterItem.remainingWork.some((work) => work.includes('全項目定義との自動突合')));
  assert.ok(!drugMasterItem.remainingWork.some((work) => work.includes('廃止薬警告')));
  assert.ok(!drugMasterItem.remainingWork.some((work) => work.includes('列定義の固定仮定')));
  assert.ok(!drugMasterItem.remainingWork.some((work) => work.includes('更新前後差分、ロールバック')));
  assert.ok(!drugMasterItem.remainingWork.some((work) => work.includes('版管理とURL自動追従')));
  assert.ok(!drugMasterItem.remainingWork.some((work) => work.includes('正式仕様PDFとの列定義自動照合')));
});

test('return and rebilling audit item tracks the monthly claim workbench', () => {
  const returnItem = OFFICIAL_AUDIT_ITEMS.find((item) => item.id === 'e2e_return_rebilling');

  assert.ok(returnItem);
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('月次請求ワークベンチ')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('CSVと引き継ぎメモ')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('受付済み請求を請求完了へ一括締め')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('一括締め監査ログ')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('一括UKE作成')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('オンライン請求受付前チェック')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('返戻対応中/出力済み/受付済み/完了済みの混入')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('受付結果CSV/TSV/固定長風テキスト/PDF抽出テキスト')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('列名ゆれ')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('取込形式')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('共通ガード')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('請求時点スナップショット')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('OCR受付')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('読み取り信頼度')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('人手確認ポイント')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('患者マスター')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('差分を確認')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('修正候補')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('スナップショット差分をCSV')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('返戻修正メモ')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('直接遷移')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('actionTarget')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('data-testid')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('返戻修正導線のブラウザE2E常設')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('導入時請求テスト')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('帳票印刷テスト')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('監査ログ証跡判定')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('ブラウザE2E実行スクリプト')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('テストデータ自動投入')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('失敗時証跡保存')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('導入時E2EのCI常設')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('発注ワークベンチ')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('未対応/発注済み')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('入庫確認CSV')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('ロット番号')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('使用期限')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('納品数量')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('drug_stocks')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('薬品マスター在庫数')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('監査ログへ残せる')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('本日完了率')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('月次請求締め率')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('日次締めCSV')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('バックアップ保存')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('確認状況')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('服薬フォロー候補')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('接触履歴')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('監査ログ')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('患者名なし')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('日次締め承認')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('署名付き監査ログ')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('月次レビュー')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('在庫不足、発注ワークベンチ入庫登録、服薬フォロー候補、問い合わせ負荷')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('責任者レビューCSV、BI JSONへ合計')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('在庫不足、入庫登録、服薬フォロー、問い合わせ負荷の前月差')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('直近6か月の内訳')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('責任者レビューCSV')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('KPI推移')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('前月比')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('複数月KPI比較')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('店舗別KPIベンチマーク')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('全店平均')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('日次締め1回あたりへ正規化')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('在庫不足、服薬フォロー候補、問い合わせ負荷')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('実行後3営業日分の日平均差')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('BI JSON')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('外部BI')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('改善アクションテンプレート')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('閉店前残タスク削減')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('実行記録')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('効果測定')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('期限間近')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('期限超過')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('担当者割当')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('店舗横断フォロー')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('未完了エスカレーション')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('延期理由')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('再期限')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('AI補助提案')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('根拠')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('信頼度')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('採用、修正、却下')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('採用率')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('フィードバック件数')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('SOAP下書き')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('AI採否ログ')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('根拠リンク')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('患者アラートの該当表示')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('S/O/A/P別件数')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('提案種別別')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('店舗別フィードバック比較')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('他店平均')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('月次CSV')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('外部分析')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('BI JSON')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('外部BI')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('高信頼度候補の却下')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('標準・制限・停止')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('処方監査、SOAP下書き、ダッシュボード予測')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('変更前後')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('AI症例レビューCLI')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('匿名ケースID')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('誤提案、安全影響')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('ダミー証跡を実症例レビューにしない')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('AI補助予測スコア')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('在庫欠品')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('薬剤師確認必須')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('個人情報なし診断JSON')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('初回セットアップのステップ別判定')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('証跡本文や対応文面を含めず')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('サポートトリアージJSON/CSV/再現メモ')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('問い合わせ優先度')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('再現手順')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('模擬障害・問い合わせ訓練レビューCLI')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('応答時間')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('エスカレーション')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('ダミー証跡を訓練OKにしない')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('障害対応・SLAレビューCLI')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('初回告知')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('更新失敗時の切り戻し判断')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('告知チェックリスト')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('ダミー証跡を障害対応OKにしない')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('リリース・更新準備レビューCLI')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('更新前バックアップ')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('戻し訓練')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('段階配信')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('配信停止判断')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('ダミー証跡を更新準備OKにしない')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('リリース後レビューCLI')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('更新後の最小確認')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('問い合わせ件数')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('エラー件数')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('告知クローズ')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('ダミー証跡を更新後レビューOKにしない')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('リリース運用受入CLI')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('同じreleaseId')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('SLA影響領域')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('実問い合わせまたは更新失敗訓練')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('責任者引き継ぎ')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('匿名確認ID')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('ダミー証跡を運用受入にしない')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('パイロットKPIレビューCLI')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('匿名店舗ID')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('返戻率')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('フォロー期限内率')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('4週間トレンド')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('パイロット正式運用判定CLI')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('責任者レビュー、停止ルール、サポート引き継ぎ')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('電子処方箋公式運用試験CLI')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('6桁引換番号')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('処方内容（控え）を原本扱いしない')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('重複投薬等チェック未実施')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('監査ログ整合性')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('ローカルパス、URL、トークンを含めず')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('公式サンプルだけで見るEX/JY/MN/ON/RC')));
  assert.ok(returnItem.implementationEvidence.some((evidence) => evidence.includes('通常請求UKE外として確認')));
  assert.ok(!returnItem.remainingWork.some((work) => work.includes('店舗別KPIベンチマーク')));
  assert.ok(returnItem.remainingWork.some((work) => work.includes('実症例レビュー')));
  assert.ok(returnItem.remainingWork.some((work) => work.includes('高信頼度の誤提案')));
  assert.ok(returnItem.remainingWork.some((work) => work.includes('パイロット正式運用判定CLI')));
  assert.ok(returnItem.remainingWork.some((work) => work.includes('電子処方箋の本番接続モジュール')));
  assert.ok(returnItem.remainingWork.some((work) => work.includes('調剤結果登録')));
  assert.ok(!returnItem.remainingWork.some((work) => work.includes('検証のみ公式種別')));
  assert.ok(returnItem.remainingWork.some((work) => work.includes('国保連')));
  assert.ok(!returnItem.remainingWork.some((work) => work.includes('帳票PDF由来テキスト')));
  assert.ok(!returnItem.remainingWork.some((work) => work.includes('日次締めCSV')));
  assert.ok(!returnItem.remainingWork.some((work) => work.includes('責任者承認')));
  assert.ok(!returnItem.remainingWork.some((work) => work.includes('日次締めの監査ログ化')));
  assert.ok(!returnItem.remainingWork.some((work) => work.includes('日次締め承認履歴の月次レビュー')));
  assert.ok(!returnItem.remainingWork.some((work) => work.includes('責任者レビューCSV')));
  assert.ok(!returnItem.remainingWork.some((work) => work.includes('KPI推移グラフ')));
  assert.ok(!returnItem.remainingWork.some((work) => work.includes('KPI推移の期間比較')));
  assert.ok(!returnItem.remainingWork.some((work) => work.includes('複数月KPI比較')));
  assert.ok(!returnItem.remainingWork.some((work) => work.includes('修正候補')));
  assert.ok(!returnItem.remainingWork.some((work) => work.includes('返戻修正導線')));
  assert.ok(!returnItem.remainingWork.some((work) => work.includes('個人情報なし診断')));
  assert.ok(!returnItem.remainingWork.some((work) => work.includes('スクリーンショット回帰')));
  assert.ok(!returnItem.remainingWork.some((work) => work.includes('画面表示')));
  assert.ok(!returnItem.remainingWork.some((work) => work.includes('月次一覧と一括UKE作成')));
  assert.ok(!returnItem.remainingWork.some((work) => work.includes('月次請求ワークベンチからの一括ステータス更新')));
  assert.ok(!returnItem.remainingWork.some((work) => work.includes('CI常設')));
  assert.ok(!returnItem.remainingWork.some((work) => work.includes('失敗時証跡保存')));
  assert.ok(!returnItem.remainingWork.some((work) => work.includes('テストデータ自動投入')));
  assert.ok(!returnItem.remainingWork.some((work) => work.includes('オンライン請求受付チェック相当')));
  assert.ok(!returnItem.remainingWork.some((work) => work.includes('返戻中や既出力')));
  assert.ok(!returnItem.remainingWork.some((work) => work.includes('受付結果ファイル取込と消込')));
  assert.ok(!returnItem.remainingWork.some((work) => work.includes('CSV/TSV以外')));
  assert.ok(!returnItem.remainingWork.some((work) => work.includes('上書きとロック済み請求の請求時点スナップショット設計')));
});

test('insurance audit item tracks eligibility period and public expense limit structure', () => {
  const insuranceItem = OFFICIAL_AUDIT_ITEMS.find((item) => item.id === 'insurance_public_expense');

  assert.ok(insuranceItem);
  assert.ok(insuranceItem.implementationEvidence.some((evidence) => evidence.includes('資格確認状態')));
  assert.ok(insuranceItem.implementationEvidence.some((evidence) => evidence.includes('患者候補')));
  assert.ok(insuranceItem.implementationEvidence.some((evidence) => evidence.includes('同姓同名')));
  assert.ok(insuranceItem.implementationEvidence.some((evidence) => evidence.includes('統合プレビュー')));
  assert.ok(insuranceItem.implementationEvidence.some((evidence) => evidence.includes('移動する受付/アラート')));
  assert.ok(insuranceItem.implementationEvidence.some((evidence) => evidence.includes('監査ログ文面')));
  assert.ok(insuranceItem.implementationEvidence.some((evidence) => evidence.includes('統合実行パッチ')));
  assert.ok(insuranceItem.implementationEvidence.some((evidence) => evidence.includes('取り消し用パッチ')));
  assert.ok(insuranceItem.implementationEvidence.some((evidence) => evidence.includes('確認リスト')));
  assert.ok(insuranceItem.implementationEvidence.some((evidence) => evidence.includes('途中失敗時')));
  assert.ok(insuranceItem.implementationEvidence.some((evidence) => evidence.includes('適用済み分だけ')));
  assert.ok(insuranceItem.implementationEvidence.some((evidence) => evidence.includes('統合確認')));
  assert.ok(insuranceItem.implementationEvidence.some((evidence) => evidence.includes('実行順')));
  assert.ok(insuranceItem.implementationEvidence.some((evidence) => evidence.includes('カードリーダー連携サービス')));
  assert.ok(insuranceItem.implementationEvidence.some((evidence) => evidence.includes('環境変数')));
  assert.ok(insuranceItem.implementationEvidence.some((evidence) => evidence.includes('デモデータ')));
  assert.ok(insuranceItem.implementationEvidence.some((evidence) => evidence.includes('外部接続先URL')));
  assert.ok(insuranceItem.implementationEvidence.some((evidence) => evidence.includes('Bearerトークン')));
  assert.ok(insuranceItem.implementationEvidence.some((evidence) => evidence.includes('デモ結果')));
  assert.ok(insuranceItem.implementationEvidence.some((evidence) => evidence.includes('接続準備')));
  assert.ok(insuranceItem.implementationEvidence.some((evidence) => evidence.includes('URLやトークンを含めない')));
  assert.ok(insuranceItem.implementationEvidence.some((evidence) => evidence.includes('直近接続試行')));
  assert.ok(insuranceItem.implementationEvidence.some((evidence) => evidence.includes('タイムアウト')));
  assert.ok(insuranceItem.implementationEvidence.some((evidence) => evidence.includes('再実行アクション')));
  assert.ok(insuranceItem.implementationEvidence.some((evidence) => evidence.includes('リクエスト本文、レスポンス本文を含めず')));
  assert.ok(insuranceItem.implementationEvidence.some((evidence) => evidence.includes('実レスポンス形式サンプル')));
  assert.ok(insuranceItem.implementationEvidence.some((evidence) => evidence.includes('差分テストの受け皿')));
  assert.ok(insuranceItem.implementationEvidence.some((evidence) => evidence.includes('レスポンス差分をCSV出力')));
  assert.ok(insuranceItem.implementationEvidence.some((evidence) => evidence.includes('個人情報を含むサンプル登録を止める')));
  assert.ok(insuranceItem.implementationEvidence.some((evidence) => evidence.includes('現地試験ゲート')));
  assert.ok(insuranceItem.implementationEvidence.some((evidence) => evidence.includes('個人情報なし共有')));
  assert.ok(insuranceItem.implementationEvidence.some((evidence) => evidence.includes('公費期限')));
  assert.ok(insuranceItem.implementationEvidence.some((evidence) => evidence.includes('負担上限未設定')));
  assert.ok(insuranceItem.implementationEvidence.some((evidence) => evidence.includes('保険者番号/公費番号')));
  assert.ok(insuranceItem.implementationEvidence.some((evidence) => evidence.includes('半角数字不備')));
  assert.ok(insuranceItem.implementationEvidence.some((evidence) => evidence.includes('本人・家族区分')));
  assert.ok(insuranceItem.implementationEvidence.some((evidence) => evidence.includes('資格確認日の未記録')));
  assert.ok(insuranceItem.implementationEvidence.some((evidence) => evidence.includes('公費負担割合')));
  assert.ok(insuranceItem.implementationEvidence.some((evidence) => evidence.includes('レスポンス')));
  assert.ok(insuranceItem.implementationEvidence.some((evidence) => evidence.includes('元項目名マッピング')));
  assert.ok(insuranceItem.implementationEvidence.some((evidence) => evidence.includes('全角数値')));
  assert.ok(insuranceItem.implementationEvidence.some((evidence) => evidence.includes('記号/番号分離')));
  assert.ok(insuranceItem.implementationEvidence.some((evidence) => evidence.includes('和暦日付')));
  assert.ok(insuranceItem.implementationEvidence.some((evidence) => evidence.includes('公費一覧')));
  assert.ok(insuranceItem.remainingWork.some((work) => work.includes('公式実レスポンス現物サンプル')));
  assert.ok(insuranceItem.remainingWork.some((work) => work.includes('公式認証方式')));
  assert.ok(insuranceItem.remainingWork.some((work) => work.includes('現地機器')));
  assert.ok(insuranceItem.remainingWork.some((work) => work.includes('現物証跡')));
  assert.ok(!insuranceItem.remainingWork.some((work) => work.includes('統合実行画面')));
  assert.ok(!insuranceItem.remainingWork.some((work) => work.includes('取り消し手順')));
  assert.ok(!insuranceItem.remainingWork.some((work) => work.includes('同姓同名患者の統合画面')));
  assert.ok(!insuranceItem.remainingWork.some((work) => work.includes('候補提示と統合画面')));
  assert.ok(!insuranceItem.remainingWork.some((work) => work.includes('公式サンプル網羅')));
  assert.ok(!insuranceItem.remainingWork.some((work) => work.includes('資格確認日、資格有効性、公費期限、負担上限の構造化')));
  assert.ok(!insuranceItem.remainingWork.some((work) => work.includes('正式レスポンス項目へのマッピング')));
  assert.ok(!insuranceItem.remainingWork.some((work) => work.includes('正式仕様サンプルによる項目名差分テスト')));
});
