import { test } from 'node:test';
import assert from 'node:assert';
import { readFileSync } from 'node:fs';

const settingsSource = readFileSync(new URL('./settings/page.tsx', import.meta.url), 'utf8');

test('settings audit tab verifies audit-log integrity and exports JSON evidence', () => {
  assert.match(settingsSource, /verifyAuditLogIntegrity/);
  assert.match(settingsSource, /buildAuditLogExportJson/);
  assert.match(settingsSource, /buildAuditLogRetentionLedgerCsv/);
  assert.match(settingsSource, /buildAuditLogRetentionManagerReviewAuditDetail/);
  assert.match(settingsSource, /buildAuditLogRetentionMonthlyReview/);
  assert.match(settingsSource, /buildAuditLogRetentionMonthlyReviewCsv/);
  assert.match(settingsSource, /AuditIntegrityReport/);
  assert.match(settingsSource, /makeAuditLogExportFileName/);
  assert.match(settingsSource, /makeAuditLogRetentionLedgerCsvFileName/);
  assert.match(settingsSource, /makeAuditLogRetentionMonthlyReviewCsvFileName/);
  assert.match(settingsSource, /buildAuditLogExportJson\(auditLogs, report, exportedAt\)/);
  assert.match(settingsSource, /ExternalConnectorReadinessReport/);
  assert.match(settingsSource, /handleExportAuditLogs/);
  assert.match(settingsSource, /handleExportAuditRetentionLedgerCsv/);
  assert.match(settingsSource, /handleExportAuditRetentionMonthlyReviewCsv/);
  assert.match(settingsSource, /監査ログ整合性/);
  assert.match(settingsSource, /監査ログJSON/);
  assert.match(settingsSource, /責任者保全欄付き/);
  assert.match(settingsSource, /保全台帳CSV/);
  assert.match(settingsSource, /監査ログ保全月次棚卸/);
  assert.match(settingsSource, /棚卸CSV/);
  assert.match(settingsSource, /責任者承認/);
  assert.match(settingsSource, /差し戻し記録/);
  assert.match(settingsSource, /data-testid="audit-retention-manager-review-button"/);
  assert.match(settingsSource, /差し戻し理由/);
  assert.match(settingsSource, /外部WORM保存確認欄付き/);
  assert.match(settingsSource, /buildOperationalClosingMonthlyReview/);
  assert.match(settingsSource, /buildOperationalClosingMonthlyReviewCsv/);
  assert.match(settingsSource, /buildOperationalClosingStoreBenchmarkActionAuditDetail/);
  assert.match(settingsSource, /buildOperationalClosingStoreBenchmarkActionPostponementAuditDetail/);
  assert.match(settingsSource, /buildOperationalClosingStoreBenchmarkBiExport/);
  assert.match(settingsSource, /makeDailyClosingReviewCsvFileName/);
  assert.match(settingsSource, /makeDailyClosingStoreBenchmarkBiExportFileName/);
  assert.match(settingsSource, /日次締め月次レビュー/);
  assert.match(settingsSource, /KPI推移/);
  assert.match(settingsSource, /日次締めKPI推移/);
  assert.match(settingsSource, /店舗別KPIベンチマーク/);
  assert.match(settingsSource, /handleExportDailyClosingStoreBenchmarkJson/);
  assert.match(settingsSource, /BI JSON/);
  assert.match(settingsSource, /日次締め前月比較/);
  assert.match(settingsSource, /日次締め複数月KPI比較/);
  assert.match(settingsSource, /monthlyKpiHistory/);
  assert.match(settingsSource, /storeBenchmark/);
  assert.match(settingsSource, /actionTemplates/);
  assert.match(settingsSource, /actionEffectSummary/);
  assert.match(settingsSource, /actionFollowUps/);
  assert.match(settingsSource, /actionFollowUpSummary/);
  assert.match(settingsSource, /actionAssignmentSummary/);
  assert.match(settingsSource, /postponingDailyClosingKpiActionId/);
  assert.match(settingsSource, /自店完了率/);
  assert.match(settingsSource, /全店平均/);
  assert.match(settingsSource, /改善アクション/);
  assert.match(settingsSource, /効果測定/);
  assert.match(settingsSource, /実行記録/);
  assert.match(settingsSource, /未実施フォロー/);
  assert.match(settingsSource, /担当者・横断フォロー/);
  assert.match(settingsSource, /横断先/);
  assert.match(settingsSource, /escalationLabel/);
  assert.match(settingsSource, /エスカレーション/);
  assert.match(settingsSource, /延期記録/);
  assert.match(settingsSource, /postponementReason/);
  assert.match(settingsSource, /期限超過/);
  assert.match(settingsSource, /期限間近/);
  assert.match(settingsSource, /優先度/);
  assert.match(settingsSource, /previousMonthComparison/);
  assert.match(settingsSource, /averageCompletionRateDeltaLabel/);
  assert.match(settingsSource, /dailyClosingReview\.allApprovals/);
  assert.match(settingsSource, /completionTrendLabel/);
  assert.match(settingsSource, /blockerTrendLabel/);
  assert.match(settingsSource, /レビューCSV/);
  assert.match(settingsSource, /承認日数/);
  assert.match(settingsSource, /残タスク日/);
  assert.match(settingsSource, /在庫不足合計/);
  assert.match(settingsSource, /入庫登録合計/);
  assert.match(settingsSource, /服薬フォロー合計/);
  assert.match(settingsSource, /問い合わせ負荷合計/);
  assert.match(settingsSource, /data-testid="daily-closing-field-kpis"/);
  assert.match(settingsSource, /data-testid="store-field-kpi-benchmark"/);
  assert.match(settingsSource, /dailyClosingReview\.totalInventoryShortages/);
  assert.match(settingsSource, /dailyClosingReview\.totalInventoryReceivings/);
  assert.match(settingsSource, /dailyClosingReview\.totalFollowUpDueCount/);
  assert.match(settingsSource, /dailyClosingReview\.totalSupportCaseCount/);
  assert.match(settingsSource, /dailyClosingComparison\.inventoryShortageDeltaLabel/);
  assert.match(settingsSource, /dailyClosingComparison\.inventoryReceivingDeltaLabel/);
  assert.match(settingsSource, /dailyClosingComparison\.followUpDueDeltaLabel/);
  assert.match(settingsSource, /dailyClosingComparison\.supportCaseDeltaLabel/);
  assert.match(settingsSource, /month\.totalInventoryShortages/);
  assert.match(settingsSource, /month\.totalInventoryReceivings/);
  assert.match(settingsSource, /month\.totalFollowUpDueCount/);
  assert.match(settingsSource, /month\.totalSupportCaseCount/);
  assert.match(settingsSource, /approval\.inventoryShortageCount/);
  assert.match(settingsSource, /approval\.inventoryReceivingCount/);
  assert.match(settingsSource, /approval\.followUpDueCount/);
  assert.match(settingsSource, /approval\.supportCaseCount/);
  assert.match(settingsSource, /averageInventoryShortageLabel/);
  assert.match(settingsSource, /averageInventoryReceivingLabel/);
  assert.match(settingsSource, /averageFollowUpDueLabel/);
  assert.match(settingsSource, /averageSupportCaseLabel/);
  assert.match(settingsSource, /allStoreAverageInventoryShortagesLabel/);
  assert.match(settingsSource, /peerAverageInventoryShortagesLabel/);
  assert.match(settingsSource, /allStoreAverageInventoryReceivingsLabel/);
  assert.match(settingsSource, /peerAverageInventoryReceivingsLabel/);
  assert.match(settingsSource, /allStoreAverageFollowUpDueLabel/);
  assert.match(settingsSource, /peerAverageFollowUpDueLabel/);
  assert.match(settingsSource, /allStoreAverageSupportCasesLabel/);
  assert.match(settingsSource, /peerAverageSupportCasesLabel/);
  assert.match(settingsSource, /inventoryShortageDeltaLabel/);
  assert.match(settingsSource, /inventoryReceivingDeltaLabel/);
  assert.match(settingsSource, /followUpDueDeltaLabel/);
  assert.match(settingsSource, /supportCaseDeltaLabel/);
  assert.match(settingsSource, /latestAuditHashPreview/);
});

test('settings audit export is permissioned and audit logged', () => {
  assert.match(settingsSource, /ensurePermission\('view_audit_logs'\)/);
  assert.match(settingsSource, /logAuditAction\(\s*db,\s*'audit_export'/);
  assert.match(settingsSource, /監査ログJSONエクスポート: \$\{fileName\} に \$\{auditLogs\.length\}件を書き出しました/);
  assert.match(settingsSource, /\/api\/system\/connector-readiness/);
  assert.match(settingsSource, /externalConnectorReadiness/);
  assert.match(settingsSource, /監査ログ保全台帳CSVエクスポート: \$\{fileName\} に最新ハッシュ/);
  assert.match(settingsSource, /監査ログ保全月次棚卸CSVエクスポート: \$\{fileName\} を書き出しました/);
  assert.match(settingsSource, /logAuditAction\(\s*db,\s*'audit_retention_approval'/);
  assert.match(settingsSource, /監査ログ保全の責任者承認を記録しました。/);
  assert.match(settingsSource, /監査ログ保全の差し戻し記録を残しました。/);
  assert.match(settingsSource, /buildBackupRestoreDrillReport/);
  assert.match(settingsSource, /buildBackupRestoreDrillAuditDetail/);
  assert.match(settingsSource, /buildBackupGenerationReview/);
  assert.match(settingsSource, /buildBackupGenerationReviewCsv/);
  assert.match(settingsSource, /buildBackupExternalStorageEvidence/);
  assert.match(settingsSource, /buildBackupExternalStorageAuditDetail/);
  assert.match(settingsSource, /buildBackupExternalStorageEvidenceFromTransferReceipt/);
  assert.match(settingsSource, /buildBackupExternalTransferManifest/);
  assert.match(settingsSource, /buildBackupExternalTransferManifestAuditDetail/);
  assert.match(settingsSource, /buildBackupExternalTransferManifestJson/);
  assert.match(settingsSource, /buildBackupScheduleReview/);
  assert.match(settingsSource, /buildBackupSchedulePolicyAuditDetail/);
  assert.match(settingsSource, /buildInitialSetupChecklist/);
  assert.match(settingsSource, /buildInitialSetupChecklistCsv/);
  assert.match(settingsSource, /buildInitialSetupHandoffMemo/);
  assert.match(settingsSource, /makeInitialSetupChecklistCsvFileName/);
  assert.match(settingsSource, /handleExportInitialSetupChecklistCsv/);
  assert.match(settingsSource, /handleCopyInitialSetupHandoffMemo/);
  assert.match(settingsSource, /初回セットアップ/);
  assert.match(settingsSource, /data-testid="initial-setup-panel"/);
  assert.match(settingsSource, /data-testid="initial-setup-next-step-button"/);
  assert.match(settingsSource, /data-testid="initial-setup-checklist-csv-button"/);
  assert.match(settingsSource, /data-testid="initial-setup-handoff-memo-button"/);
  assert.match(settingsSource, /initial-setup-step-\$\{step\.id\}/);
  assert.match(settingsSource, /initial-setup-required-actions/);
  assert.match(settingsSource, /step\.requiredActions\.slice\(0, 2\)/);
  assert.match(settingsSource, /初回セットアップチェックリストCSVエクスポート/);
  assert.match(settingsSource, /初回セットアップ引き継ぎメモコピー/);
  assert.match(settingsSource, /チェックリストCSV/);
  assert.match(settingsSource, /引き継ぎメモ/);
  assert.match(settingsSource, /新規店舗のテスト運用開始/);
  assert.match(settingsSource, /readBackupSchedulePolicy/);
  assert.match(settingsSource, /writeBackupSchedulePolicy/);
  assert.match(settingsSource, /makeBackupGenerationReviewCsvFileName/);
  assert.match(settingsSource, /makeBackupExternalTransferManifestFileName/);
  assert.match(settingsSource, /validateBackupExternalTransferReceipt/);
  assert.match(settingsSource, /migrationDiagnostic/);
  assert.match(settingsSource, /buildPatientCsvMigrationPreview/);
  assert.match(settingsSource, /buildVisitCsvMigrationPreview/);
  assert.match(settingsSource, /buildDrugStockCsvMigrationPreview/);
  assert.match(settingsSource, /buildSoapCsvMigrationPreview/);
  assert.match(settingsSource, /buildDrugMasterUpdateArtifacts/);
  assert.match(settingsSource, /buildDrugMasterDiffCsv/);
  assert.match(settingsSource, /makeDrugMasterDiffCsvFileName/);
  assert.match(settingsSource, /makeDrugMasterRollbackFileName/);
  assert.match(settingsSource, /validateDrugMasterRollbackPayload/);
  assert.match(settingsSource, /parseDrugMasterUpdateCsv/);
  assert.match(settingsSource, /extractDrugMasterCsvFromZip/);
  assert.match(settingsSource, /isDrugMasterZipUpload/);
  assert.match(settingsSource, /handleImportDrugMasterFromSourceUrl/);
  assert.match(settingsSource, /canImportDrugMasterFromSourceUrl/);
  assert.match(settingsSource, /\/api\/drug-master\/official-file/);
  assert.match(settingsSource, /DRUG_MASTER_SPECIFICATION_SOURCE/);
  assert.match(settingsSource, /buildDrugMasterColumnDefinitionReview/);
  assert.match(settingsSource, /buildDrugMasterSpecificationRevisionReview/);
  assert.match(settingsSource, /parsedMasterCsv\.maxColumnCount/);
  assert.match(settingsSource, /formatDrugMasterColumnDefinitionReview/);
  assert.match(settingsSource, /formatDrugMasterSpecificationRevisionReview/);
  assert.match(settingsSource, /formatDrugMasterCsvLayoutLabel/);
  assert.match(settingsSource, /buildDrugMasterSpecificationPdfDiffReview/);
  assert.match(settingsSource, /formatDrugMasterSpecificationPdfDiffReview/);
  assert.match(settingsSource, /DrugMasterSpecificationPdfDiffReview/);
  assert.match(settingsSource, /DrugMasterOfficialSpecPdfFetchResult/);
  assert.match(settingsSource, /buildDrugMasterSourceEvidence/);
  assert.match(settingsSource, /extractSskDrugMasterDownloadCandidates/);
  assert.match(settingsSource, /DrugMasterOfficialPageFetchResult/);
  assert.match(settingsSource, /normalizeDrugMasterSourceUrl/);
  assert.match(settingsSource, /reviewDrugMasterSourceUrl/);
  assert.match(settingsSource, /formatDrugMasterSourceUrlReview/);
  assert.match(settingsSource, /handleExportBackupGenerationReviewCsv/);
  assert.match(settingsSource, /handleRecordBackupExternalStorage/);
  assert.match(settingsSource, /handleSaveBackupSchedulePolicy/);
  assert.match(settingsSource, /handleRecordBackupDrill/);
  assert.match(settingsSource, /handleApplyDrugMasterRollback/);
  assert.match(settingsSource, /logAuditAction\(\s*db,\s*'backup_drill'/);
  assert.match(settingsSource, /logAuditAction\(\s*db,\s*'backup_external_storage'/);
  assert.match(settingsSource, /logAuditAction\(\s*db,\s*'backup_external_transfer_manifest'/);
  assert.match(settingsSource, /logAuditAction\(\s*db,\s*'backup_schedule_update'/);
  assert.match(settingsSource, /sourceExtractionLabel/);
  assert.match(settingsSource, /sourceFileType/);
  assert.match(settingsSource, /extractedCsvFileName/);
  assert.match(settingsSource, /specificationRevisionReviewLabel/);
  assert.match(settingsSource, /specificationSourceUrl: DRUG_MASTER_SPECIFICATION_SOURCE\.url/);
  assert.match(settingsSource, /支払基金マスタ同期: 支払基金の最新医薬品マスターCSVからマスタを更新しました（版: \$\{artifacts\.versionId\}, 入力: \$\{sourceExtractionLabel\}, 列定義: \$\{layoutLabel\}/);
  assert.match(settingsSource, /列定義照合: \$\{columnDefinitionReviewLabel\}/);
  assert.match(settingsSource, /仕様PDF版: \$\{specificationRevisionReviewLabel\}/);
  assert.match(settingsSource, /公式URL確認: \$\{sourceUrlReviewLabel\}/);
  assert.match(settingsSource, /仕様PDF版OK/);
  assert.match(settingsSource, /SHA-256: \$\{sourceEvidence\.sha256\}/);
  assert.match(settingsSource, /更新元URL: \$\{sourceEvidence\.sourceUrl \|\| '未入力'\}/);
  assert.match(settingsSource, /差分CSV \$\{diffCsvFileName\} とロールバックJSON \$\{rollbackFileName\} を書き出しました/);
  assert.match(settingsSource, /医薬品マスターロールバック: 版 \$\{payload\.versionId\}/);
  assert.match(settingsSource, /復旧テスト（訓練）レポート/);
  assert.match(settingsSource, /復旧テストを記録/);
  assert.match(settingsSource, /バックアップ世代管理/);
  assert.match(settingsSource, /閉店時バックアップ予定/);
  assert.match(settingsSource, /導入移行診断/);
  assert.match(settingsSource, /移行CSVをプレビュー/);
  assert.match(settingsSource, /患者CSV移行マッピング/);
  assert.match(settingsSource, /受付CSV移行マッピング/);
  assert.match(settingsSource, /在庫CSV移行マッピング/);
  assert.match(settingsSource, /薬歴CSV移行マッピング/);
  assert.match(settingsSource, /CSVを変換してプレビュー/);
  assert.match(settingsSource, /変換JSONを保存/);
  assert.match(settingsSource, /ID欠落/);
  assert.match(settingsSource, /同一ID重複/);
  assert.match(settingsSource, /文字化け疑い/);
  assert.match(settingsSource, /必須領域不足/);
  assert.match(settingsSource, /予定を保存/);
  assert.match(settingsSource, /世代管理CSV/);
  assert.match(settingsSource, /バックアップ世代管理CSVエクスポート/);
  assert.match(settingsSource, /外部保存を確認する/);
  assert.match(settingsSource, /外部保存を記録/);
  assert.match(settingsSource, /外部保存連携JSONも出力する/);
  assert.match(settingsSource, /保存先保持日数/);
  assert.match(settingsSource, /受領書JSONを選択/);
  assert.match(settingsSource, /受領書を監査ログへ記録/);
  assert.match(settingsSource, /最新外部保存確認/);
  assert.match(settingsSource, /医薬品マスターロールバック/);
  assert.match(settingsSource, /ヘッダー付きCSVは列名を確認/);
  assert.match(settingsSource, /ファイルを選択 \(CSV\/ZIP\)/);
  assert.match(settingsSource, /accept="\.csv,\.zip"/);
  assert.match(settingsSource, /ZIPは中のCSVを展開/);
  assert.match(settingsSource, /更新元URLから取得して更新/);
  assert.match(settingsSource, /取得・更新中/);
  assert.match(settingsSource, /更新元URL（任意）/);
  assert.match(settingsSource, /支払基金ページHTML/);
  assert.match(settingsSource, /handleFetchDrugMasterOfficialPage/);
  assert.match(settingsSource, /\/api\/drug-master\/official-page/);
  assert.match(settingsSource, /公式ページを取得/);
  assert.match(settingsSource, /更新候補を抽出/);
  assert.match(settingsSource, /drugMasterSpecPdfText/);
  assert.match(settingsSource, /isFetchingDrugMasterSpecPdf/);
  assert.match(settingsSource, /handleFetchDrugMasterSpecPdf/);
  assert.match(settingsSource, /\/api\/drug-master\/official-spec-pdf/);
  assert.match(settingsSource, /handleReviewDrugMasterSpecPdfText/);
  assert.match(settingsSource, /医薬品マスター仕様PDF本文照合/);
  assert.match(settingsSource, /公式PDFを取得して照合/);
  assert.match(settingsSource, /PDF本文を照合/);
  assert.match(settingsSource, /支払基金マスター更新候補一覧/);
  assert.match(settingsSource, /handleSelectDrugMasterCandidate/);
  assert.match(settingsSource, /更新元URLへ反映/);
  assert.match(settingsSource, /ファイルサイズ、SHA-256/);
  assert.match(settingsSource, /差分CSVとロールバックJSON/);
  assert.match(settingsSource, /ロールバックJSONを選択/);
  assert.match(settingsSource, /ロールバックを実行/);
  assert.match(settingsSource, /日次締め月次レビューCSVエクスポート/);
  assert.match(settingsSource, /日次締め月次レビューCSVを書き出しました/);
  assert.match(settingsSource, /店舗別KPIベンチマークJSONエクスポート/);
  assert.match(settingsSource, /外部BI連携用/);
  assert.match(settingsSource, /handleRecordDailyClosingKpiAction/);
  assert.match(settingsSource, /logAuditAction\(\s*db,\s*'daily_closing_kpi_action'/);
  assert.match(settingsSource, /KPI改善アクション/);
  assert.match(settingsSource, /AI補助フィードバック月次レビュー/);
  assert.match(settingsSource, /buildAiSuggestionFeedbackMonthlyReview/);
  assert.match(settingsSource, /buildAiSuggestionFeedbackMonthlyReviewCsv/);
  assert.match(settingsSource, /buildAiSuggestionFeedbackBiExport/);
  assert.match(settingsSource, /makeAiSuggestionFeedbackReviewCsvFileName/);
  assert.match(settingsSource, /makeAiSuggestionFeedbackBiExportFileName/);
  assert.match(settingsSource, /handleExportAiSuggestionFeedbackReviewCsv/);
  assert.match(settingsSource, /handleExportAiSuggestionFeedbackBiJson/);
  assert.match(settingsSource, /採用率/);
  assert.match(settingsSource, /平均信頼度/);
  assert.match(settingsSource, /SOAP下書き品質レビュー/);
  assert.match(settingsSource, /soapDraftSummary/);
  assert.match(settingsSource, /提案種別別/);
  assert.match(settingsSource, /domainSummaries/);
  assert.match(settingsSource, /S\/O\/A\/P/);
  assert.match(settingsSource, /店舗別フィードバック比較/);
  assert.match(settingsSource, /storeComparison/);
  assert.match(settingsSource, /自店採用率/);
  assert.match(settingsSource, /他店平均/);
  assert.match(settingsSource, /フィードバックCSV/);
  assert.match(settingsSource, /BI JSON/);
  assert.match(settingsSource, /data-testid="ai-quality-gate"/);
  assert.match(settingsSource, /高信頼度/);
  assert.match(settingsSource, /推奨モードを反映/);
  assert.match(settingsSource, /handleApplyAiQualityRecommendation/);
  assert.match(settingsSource, /currentAiAssistMode/);
  assert.match(settingsSource, /AI補助フィードバック月次レビューCSVエクスポート: \$\{fileName\} に \$\{review\.totalCount\}件の採否ログ/);
  assert.match(settingsSource, /AI補助フィードバックBI JSONエクスポート: \$\{fileName\} に \$\{review\.totalCount\}件の採否ログ/);
  assert.match(settingsSource, /audit_export: '監査ログ書出'/);
  assert.match(settingsSource, /audit_retention_approval: '監査ログ保全確認'/);
  assert.match(settingsSource, /backup_schedule_update: 'バックアップ予定変更'/);
  assert.match(settingsSource, /backup_external_storage: '外部保存確認'/);
  assert.match(settingsSource, /backup_external_transfer_manifest: '外部保存連携JSON'/);
  assert.match(settingsSource, /backup_drill: '復旧テスト'/);
  assert.match(settingsSource, /follow_up_record: '服薬フォロー記録'/);
  assert.match(settingsSource, /ai_suggestion_review: 'AI補助提案確認'/);
  assert.match(settingsSource, /daily_closing_approval: '日次締め承認'/);
  assert.match(settingsSource, /daily_closing_kpi_action: 'KPI改善アクション'/);
  assert.match(settingsSource, /<option value="audit_export">監査ログ書出<\/option>/);
  assert.match(settingsSource, /<option value="audit_retention_approval">監査ログ保全確認<\/option>/);
  assert.match(settingsSource, /<option value="backup_schedule_update">バックアップ予定変更<\/option>/);
  assert.match(settingsSource, /<option value="backup_external_storage">外部保存確認<\/option>/);
  assert.match(settingsSource, /<option value="backup_external_transfer_manifest">外部保存連携JSON<\/option>/);
  assert.match(settingsSource, /<option value="backup_drill">復旧テスト<\/option>/);
  assert.match(settingsSource, /<option value="follow_up_record">服薬フォロー記録<\/option>/);
  assert.match(settingsSource, /<option value="ai_suggestion_review">AI補助提案確認<\/option>/);
  assert.match(settingsSource, /<option value="daily_closing_approval">日次締め承認<\/option>/);
  assert.match(settingsSource, /<option value="daily_closing_kpi_action">KPI改善アクション<\/option>/);
});

test('settings labels official source checks as specification review', () => {
  assert.match(settingsSource, /公式仕様点検/);
  assert.match(settingsSource, /公開資料に照らした/);
  assert.doesNotMatch(settingsSource, /公式監査/);
});

test('settings runs and exports the dispensing UKE PDF all-field review', () => {
  assert.match(settingsSource, /parseDispensingUkeSpecificationPdfText/);
  assert.match(settingsSource, /buildDispensingUkeSpecificationPdfFieldDefinitionReview/);
  assert.match(settingsSource, /buildDispensingUkeSpecificationPdfAllFieldCompletionGate/);
  assert.match(settingsSource, /buildDispensingUkeSpecificationPdfAllFieldCompletionGateCsv/);
  assert.match(settingsSource, /buildDispensingUkeOfficialAllFieldDefinitionGate/);
  assert.match(settingsSource, /buildDispensingUkeOfficialAllFieldDefinitionGateCsv/);
  assert.match(settingsSource, /formatDispensingUkeOfficialAllFieldDefinitionGate/);
  assert.match(settingsSource, /buildDispensingUkeSpecificationPdfAllFieldImplementationPack/);
  assert.match(settingsSource, /buildDispensingUkeSpecificationPdfAllFieldImplementationPackText/);
  assert.match(settingsSource, /parseDispensingUkeSpecConfirmationText/);
  assert.match(settingsSource, /\/api\/receipt\/official-spec-pdf/);
  assert.match(settingsSource, /公式提出UKE allFields完了ゲート/);
  assert.match(settingsSource, /data-testid="dispensing-uke-official-all-fields-gate"/);
  assert.match(settingsSource, /data-testid="dispensing-uke-official-all-fields-gate-status"/);
  assert.match(settingsSource, /data-testid="dispensing-uke-official-all-fields-gate-csv-button"/);
  assert.match(settingsSource, /公式提出UKE allFields完了ゲートCSV書出/);
  assert.match(settingsSource, /UKE仕様PDF 全項目確認/);
  assert.match(settingsSource, /data-testid="dispensing-uke-spec-review"/);
  assert.match(settingsSource, /data-testid="dispensing-uke-spec-fetch-button"/);
  assert.match(settingsSource, /data-testid="dispensing-uke-spec-review-button"/);
  assert.match(settingsSource, /data-testid="dispensing-uke-spec-review-csv-button"/);
  assert.match(settingsSource, /data-testid="dispensing-uke-spec-implementation-pack-button"/);
  assert.match(settingsSource, /UKE仕様PDF実装パック書出/);
  assert.match(settingsSource, /logAuditAction\(\s*db,\s*'official_spec_review'/);
  assert.match(settingsSource, /official_spec_review: '公式仕様点検'/);
  assert.match(settingsSource, /<option value="official_spec_review">公式仕様点検<\/option>/);
});
